### ISSUE TITLE
ThinkAgent

### ISSUE THREAD

**Issue by dmitrijsk** [salesforce/BOLAA#8]
Hi, according to the paper, the BOLAA's labor agents pool consists of two agents, `SearchAgent` and `ClickAgent`:

>Regarding BOLAA, we devise one search LAA and one click LAA to generate search query and click elements,
respectively. 

However, the architecture file also [contains](https://github.com/salesforce/BOLAA/blob/main/web_run/multi_agent_arch.py#L106) the `ThinkAgent`, which does not seem to be used anywhere. Could you please clarify, why did you decide to leave it out of the agents pool?

Thank you!

**Comment by JimSalesforce** [comment]
Thanks for asking. In the paper, we also mentioned that, "Note that we can also design those labor LAAs to be think/plan agent. In this way, the self-think and plan work flows are also retained." The thinkAgent can be inserted into the controller as the think flow (like ReAct). You may also design a PlanAgent in the same way to enable the plan flow. We did some test but due to time limit, not in a comprehensive way. Feel free to implement it by your self. We may include these into the BOLAA architecture later.

**Comment by dmitrijsk** [comment]
Many thanks for your answer!
